# Generated by Django 4.0.4 on 2022-04-20 14:10

from django.db import migrations, models
import django.db.models.deletion
import mailing.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, validators=[mailing.validators.PhoneNumberValidator], verbose_name='Номер телефона')),
                ('operator_id', models.CharField(max_length=20, verbose_name='Код мобильного оператора')),
                ('tag', models.CharField(max_length=20, verbose_name='Тэг')),
                ('timezone', models.CharField(max_length=10, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('launch_at', models.DateTimeField(verbose_name='Дата и время запуска рассылки')),
                ('text', models.TextField(verbose_name='Текст сообщения для доставки клиенту')),
                ('mailing_filter', models.CharField(max_length=20, verbose_name='Фильтр для рассылки (код моб оператора + тэг)')),
                ('terminate_at', models.DateTimeField(verbose_name='Дата и время окончания рассылки')),
            ],
            options={
                'verbose_name': 'Рассылки',
                'verbose_name_plural': 'Рассылки',
                'ordering': ['launch_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания (отправки)')),
                ('status', models.CharField(max_length=10, verbose_name='Статус отправки')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.client', verbose_name='ID клиента')),
                ('mailing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mailing.mailing', verbose_name='ID рассылки')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
                'ordering': ['-created_at'],
            },
        ),
    ]
